name: Scheduled Python Script

on:
  schedule:
    - cron: '00 21 * * *'  # Runs at 20:00 UTC, which is 3 AM in China (UTC+8)
  workflow_dispatch:  # This line enables manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx[http2]

    - name: Run script
      env:
        USERNAME: ${{ secrets.MY_USERNAME }}
        PASSWORD: ${{ secrets.MY_PASSWORD }}
      run: |
        python 4ksj.py
